# This is the developer docker-compose.yml file. You can build and Run ChurchCRM
# from this file by first filling in your password and db info in the .env
# file and then running "docker-compose -f docker-compose.develop.yaml build", and
# "docker-compose -f docker-compose.develop.yaml up" in your terminal.
version: "3"
services:
  database:
    image: mariadb
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
  churchcrm:
    build:
      context: .
      dockerfile: Dockerfile.churchcrm-debian
    # ports:
    #   - "9000:9000"
    volumes:
      - source:/var/www/html
    env_file:
      - .env
    links:
      - database
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    links:
      - churchcrm
    volumes:
      - source:/var/www/html
  coder:
    image: codercom/code-server:1.621
    volumes:
      - source:/home/coder/project
      - coder_data:/home/coder
    ports:
      - "443:8443"
volumes:
  source:
  db-volume: null
  coder_data: null
